import Head from "next/head";
import React, { useCallback } from "react";
import { useRouter } from "next/router";

export default function Home() {
  const router = useRouter();

  const onClickLogin = useCallback((e: React.MouseEvent<HTMLButtonElement>) => {
    e.preventDefault();
    router.push("/login");
  }, []);

  const onClickMain = useCallback((e: React.MouseEvent<HTMLButtonElement>) => {
    e.preventDefault();
    router.push("/main");
  }, []);

  return (
    <>
      <Head>
        <title>G Ware 2023</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <ul>
        <li>
          <button onClick={onClickLogin}>로그인 페이지</button>
        </li>
        <li>
          <button onClick={onClickMain}>메인 페이지</button>
        </li>
      </ul>
    </>
  );
}
