import Head from "next/head";
import MainTemplate from "../components/main/MainTemplate";
import Dashboard from "../components/dashboard/Dashboard";

export default function Home() {
  return (
    <>
      <Head>
        <title>G Ware 2023</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>

      <MainTemplate
        title="Dashboard"
        elements={["Post", "Project", "Organization"]}
      >
        {<Dashboard />}
      </MainTemplate>
    </>
  );
}
